name: Build

on:
  push:
    tags:
      - deploy-[a-f0-9]{40}@hpny-staging
      - deploy-[a-f0-9]{40}@hpny-test
      - deploy-[a-f0-9]{40}@hpny-uat
      - deploy-[a-f0-9]{40}@hpny-production
      - deploy-[a-f0-9]{40}@hpsf-staging
      - deploy-[a-f0-9]{40}@hpsf-test
      - deploy-[a-f0-9]{40}@hpsf-uat
      - deploy-[a-f0-9]{40}@hpsf-production

env:
  CI: true
  NODE_VERSION: '12.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Dump GITHUB_REF
      run: echo "$GITHUB_REF"
    - name: Dump environment variables
      run: env | sort
    - name: Dump GITHUB & RUNNER environment variables
      run: env | egrep '^(GITHUB|RUNNER)_' | sort
    - name: Confirm shell
      run: echo '$0:' $0
    - name: Examine shell
      run: ls -l $0 ; wc -l $0 ; echo 'Contents of $0:' ; while read -r line; do echo $line; done < $0
    - name: Examine PWD
      run: echo $PWD ; ls -ltra ; find .
    - name: Extract string from Git tag ref e.g. 'refs/tags/foo.0.0.2' -> 'foo'
      run: tag=${GITHUB_REF/*tags\//} ; str=${tag/.*/} ; echo 'Extracted string:' $str
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
